var noun = {
	"angels": [
		["O", "Anjo"],
		["Os", "Anjos"],
		["O", "Alado"],
		["Os", "Alados"],
		["O", "Arcanjo"],
		["Os", "Arcanjos"],
		["O", "Querubim"],
		["Os", "Querubins"],
		["A", "Legião"],
		["O", "Demônio"],
		["O", "Espírito"],
		["Os", "Espíritos"]
	],
	"kings": [
		["O", "Rei"],
		["Os", "Reis"],
		["A", "Rainha"],
		["As", "Rainhas"],
		["O", "Príncipe"],
		["A", "Princesa"],
		["O", "Trono"],
		["O", "Imperador"],
		["A", "Linhagem"],
		["O", "Conde"]
	],
	"gods": [
		["O", "Deus"],
		["Os", "Deuses"],
		["O", "Panteão"],
		["A", "Irmandade"],
		["A", "Doutrina"],
		["O", "Santo"],
		["Os", "Santos"],
		["O", "Demônio"],
		["Os", "Demônios"],
		["A", "Religião"],
		["A", "Crença"],
		["A", "Seita"]
	],
	"vampires": [
		["O", "Vampiro"],
		["Os", "Vampiros"],
		["O", "Sangue"],
		["As", "Prezas"]
	],
	"war": [
		["A", "Guerra"],
		["As", "Guerras"],
		["A", "Batalha"],
		["As", "Batalhas"],
		["O", "General"],
		["O", "Guerreiro"],
		["Os", "Guerreiros"],
		["As", "Armas"],
		["A", "Lança"],
		["A", "Adaga"],
		["O", "Comandante"]
	],
	"magic": [
		["O", "Mago"],
		["A", "Magia"],
		["O", "Feiticeiro"],
		["Os", "Feiticeiros"],
		["O", "Druida"],
		["Os", "Druidas"],
		["O", "Encantador"],
		["A", "Varinha"],
		["O", "Cajado"],
		["As", "Fadas"],
		["A", "Canção"],
		["O", "Alquimista"],
		["O", "Ilusionista"],
		["O", "Telepata"]
	],
	"standard": [
		["A", "Cidade"],
		["A", "Cidadela"],
		["A", "Morte"],
		["O", "Inimigo"],
		["A", "Terra"],
		["O", "Último"],
		["O", "Sábio"],
		["As", "Chamas"],
		["As", "Crônicas"],
		["O", "Viajante"],
		["A", "Lenda"],
		["Os", "Monstros"],
		["O", "Monstro"],
		["As", "Lágrimas"],
		["As", "Areias"],
		["Os", "Olhos"],
		["O", "Herege"],
		["O", "Vale"],
		["A", "Casa"],
		["O", "Livro"],
		["O", "Poder"]
	],
	"medieval": [
		["A", "Espada"],
		["As", "Espadas"],
		["O", "Machado"],
		["Os", "Machados"],
		["O", "Escudo"],
		["Os", "Escudos"],
		["O", "Cavaleiro"],
		["O", "Arqueiro"],
		["O", "Matador"],
		["O", "Gigante"],
		["O", "Dragão"],
		["Os", "Dragões"],
		["O", "Pergaminho"],
		["Os", "Pergaminhos"],
		["O", "Senhor"],
		["Os", "Senhores"],
		["O", "Senhorio"],
		["O", "Vassalo"],
		["O", "Bardo"],
		["O", "Contador de Histórias"],
		["O", "Condenado"],
		["A", "Muralha"],
		["O", "Anão"],
		["Os", "Anões"],
		["O", "Elfo"],
		["Os", "Elfos"]
	],
	"werewolves": [
		["O", "Lobo"],
		["Os", "Lobos"],
		["O", "Cão"],
		["O", "Lobisomem"]
	]
};

var adj = {
	"angels": [
		["dos", "Anjos"],
		["do", "Céu"],
		["do", "Paraíso"],
		["do", "Inferno"],
		["do", "Ódio"],
		["do", "Apocalipse"],
		["do", "Amor"],
		["de", "Deus"],
		["de", "Éter"]
	],
	"kings": [
		["do", "Trono"],
		["do", "Reino"],
		["da", "Coroa"],
		["do", "Castelo"],
		["do", "Reino"],
		["do", "Império"],
		["do", "Palácio"],
		["da", "Corte"],
		["dos", "Reis"]
	],
	"gods": [
		["dos", "Deuses"],
		["da", "Onisciência"],
		["da", "Onipresença"],
		["da", "Onipotência"],
		["da", "Ressurreição"],
		["do", "Poder"]
	],
	"vampires": [
		["do", "Sangue"],
		["das", "Sombras"],
		["da", "Escuridão"],
		["de", "Rubi"]
	],
	"war": [
		["da", "Guerra"],
		["da", "Paz"],
		["da", "Coragem"],
		["da", "Justiça"]
	],
	"magic": [
		["da", "Magia"],
		["da", "Ilusão"]
	],
	"standard": [
		["de", "Fogo"],
		["do", "Fogo"],
		["da", "Água"],
		["de", "Gelo"],
		["da", "Luz"],
		["de", "Fogo Verde"],
		["do", "Sol"],
		["das", "Trevas"],
		["da", "Escuridão"],
		["de", "Almas"],
		["do", "Mar"],
		["da", "Noite"],
		["da", "Noite Fria"],
		["do", "Tempo"],
		["da", "Terra"],
		["da", "Areia"],
		["do", "Universo"],
		["de", "Ouro"],
		["de", "Prata"],
		["de", "Bronze"],
		["de", "Cristal"],
		["de", "Diamante"],
		["da", "Lua"],
		["da", "Verdade"],
		["das", "Cinzas"],
		["da", "Paixão"],
		["do", "Inverno"],
		["da", "Primavera"],
		["da", "Colina"],
		["das", "Colinas"],
		["da", "Montanha"],
		["das", "Montanhas"],
		["do", "Vale"],
		["de", "Preto"],
		["de", "Branco"],
		["de", "Preto e Branco"]
	],
	"medieval": [
		["dos", "Antepassados"],
		["da", "Herança"],
		["de", "Espadas"],
		["da", "Máscara de Prata"],
		["do", "Norte"],
		["do", "Sul"],
		["da", "Liberdade"]
	]
}

